# Generated by Django 4.1.3 on 2023-06-21 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0002_rename_email_person_email_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
