# Generated by Django 4.1.3 on 2023-06-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0003_person_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='creation_date',
        ),
    ]
